### ISSUE TITLE
Writer process ended unexpetedly

### ISSUE THREAD

**Issue by vamp111** [balena-io-modules/etcher-image-write#106]
i get this error when trying to write on a brand new SD, after this the card becomes unrecognizable, windows doesn't see the card, can't format it! I've tried with 2nd card, which was used many times, got the same error, now again the card is unrecognizable. Anyone had this problem ? a way to restore my SDcard ?

**Comment by lurch** [comment]
Are you _really_ using `etcher-image-write` (see #104 ) or did you mean to post this at https://github.com/balena-io/etcher/issues ? :wink: 

See https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives

**Comment by vamp111** [comment]
sorry...

**Comment by lurch** [comment]
No need to apologise, I hope you manage to get your problem sorted out :+1:

**Comment by vamp111** [comment]
I haven't :( followed the guide to recover the SD card but it didnt worked... problem is i need to update my Pi and i deffinately need to flash the OS on a new card

**Comment by lurch** [comment]
This can probably be closed as it's been moved to https://github.com/balena-io/etcher/issues/2713
